version: '3'

services:

  frontend:
    container_name: frontend
    image: front_image
    build:
      context: front
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "3001:3000"
      - "24678:24678"
    depends_on:
      - backend
    restart: always

  backend:
    container_name: backend
    image: back_image
    build:
      context: back
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      database:
        condition: service_healthy
    restart: always


  database:
    container_name: database
    image: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    # volumes:
    #   - ./postgres_volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5


