version: '3'

services:

  frontend:
    build:
      target: dev
      args:
        - NODE_ENV=development
    ports:
      - "${DEV_BIND_ADDRESS:-127.0.0.1}:3001:3000"
      - "${DEV_BIND_ADDRESS:-127.0.0.1}:24678:24678"
    volumes:
      - ./front/:/app
    env_file:
      - .env
      - .env.dev

  backend:
    build:
      target: dev
      args:
        - NODE_ENV=development
    ports:
      - "${DEV_BIND_ADDRESS:-127.0.0.1}:3000:3000"
    volumes:
      - ./back/:/app
    env_file:
      - .env
      - .env.dev

  proxy:
    environment:
      - NODE_ENV=development
    restart: "no"

  prisma-studio:
    image: timothyjmiller/prisma-studio:latest
    container_name: prisma-studio
    ports:
      - "127.0.0.1:5555:5555"
    restart: always
    env_file:
      - .env
      - .env.dev
    depends_on:
      database:
        condition: service_healthy
    entrypoint: ['node_modules/.bin/prisma', 'studio']
    volumes:
      - ./back/prisma/schema.prisma:/schema.prisma
    networks:
      - db-prisma_studio

  database:
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}"]
      interval: 1s
      timeout: 5s
      retries: 5
    networks:
      - db-prisma_studio

networks:
    db-prisma_studio:
        driver: bridge