name: Lint
on:
  push:
    branches:
      - 'main'
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: |
          npm install @typescript-eslint/eslint-plugin@6.0.0
          npm install @typescript-eslint/parser@6.0.0
          npm install eslint@8.42.0
          npm install eslint-config-prettier@9.0.0
          npm install eslint-plugin-prettier@5.0.0
        working-directory: ./back

      - name: Run Linter
        run: npm run lint
        working-directory: ./back